AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'

Documentation:
    Enabled: false

Rails:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/NestedGroups:
  Max: 4

require: rubocop-rspec
