version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    image: AMART/SIMIROUTE:0.1
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./file_storage:/app/public/system/
      - assets:/app/public/assets/
    ports:
      - 3000
    env_file:
      - .env
    environment:
      - SECRET_KEY_BASE=d0655dc0-9e5d-41ca-9738-f0f4cf388578
    depends_on:
      - db

    nginx:
      image: nginx
      volumes_from:
        - app
      depends_on:
        - app
      ports:
        - 80
      volumes:
        - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
      networks:
        default:
        nginx_default:
          aliases:
            - SIMIROUTE


volumes:
  assets:
  postgres:
networks:
  nginx_default:
    external: true
