default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  username: postgres

development:
  <<: *default
  database: simiroute_development

test:
  <<: *default
  database: simiroute_test

production:
  <<: *default
  database: simiroute_production

