version: 1
task_definition:
  ecs_network_mode: bridge

  task_size:
    cpu_limit: 768 # 896
    mem_limit: 0.5GB # 900

  services:
    web_server:
      essential: true
    web:
      essential: true
